name: accessibility-alt-text-bot
on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  discussion:
    types: [created, edited]
  discussion_comment:
    types: [created, edited]

permissions:
  issues: write
  pull-requests: write
  discussions: write

jobs:
  accessibility_alt_text_bot:
    runs-on: ubuntu-latest
    steps:
       - uses: github/accessibility-alt-text-bot@v1.4.0
